### ISSUE TITLE
unable to build with go1.14.2 

### ISSUE THREAD

**Issue by ip75** [lukasmartinelli/pgfutter#70]
C:\pgfutter.git>go build
 _/C/pgfutter.git
.\pgfutter.go:21:16: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
.\pgfutter.go:37:6: c.GlobalBool undefined (type *cli.Context has no field or method GlobalBool)
.\pgfutter.go:50:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
.\pgfutter.go:54:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
.\pgfutter.go:56:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
.\pgfutter.go:60:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
.\pgfutter.go:62:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
.\pgfutter.go:66:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
.\pgfutter.go:68:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
        cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
.\pgfutter.go:72:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
.\pgfutter.go:68:17: too many errors

C:\pgfutter.git>go version
go version go1.14.2 windows/amd64

**Comment by root0x** [comment]
Has this issue been resolve having this problem on alpine with go 1.16
