### ISSUE TITLE
build failures on master

### ISSUE THREAD

**Issue by pushcx** [lukasmartinelli/pgfutter#69]
I don't know golang. Searches imply something has changed in how golang handles modules?

```
$ go version
go version go1.14.1 linux/amd64
```

```
$ go build
# _/home/pushcx/pgfutter
./pgfutter.go:21:16: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
./pgfutter.go:36:6: c.GlobalBool undefined (type *cli.Context has no field or method GlobalBool)
./pgfutter.go:49:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./pgfutter.go:53:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
./pgfutter.go:55:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./pgfutter.go:59:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
./pgfutter.go:61:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./pgfutter.go:65:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
./pgfutter.go:67:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
./pgfutter.go:71:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
./pgfutter.go:67:17: too many errors
```

**Comment by danieldjewell** [comment]
Hi @pushcx 

I ran into this too - There were some API changes in a few modules used by pgfutter... I updated them. The fork in my repo should build on Go 1.14 and 1.13 without issue: ```go get github.com/danieldjewell/pgfutter``` (note: I have *not* done extensive testing of this...) 

@lukasmartinelli Not trying to steal the project, I'm just not sure of another way to have the project build without pushing it to my repo's master ("go get" is funny like that - it doesn't seem possible to specify a branch...)

**Comment by patrick-webs** [comment]
@danieldjewell it seems like your fork is broken similarly now on go version go1.14 darwin/amd64...

```
~/ go get github.com/danieldjewell/pgfutter
# github.com/danieldjewell/pgfutter
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:21:16: c.GlobalString undefined (type *cli.Context has no field or method GlobalString)
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:36:6: c.GlobalBool undefined (type *cli.Context has no field or method GlobalBool)
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:49:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:53:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:55:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:59:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:61:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:65:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:67:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:71:4: unknown field 'EnvVar' in struct literal of type cli.StringFlag
go/src/github.com/danieldjewell/pgfutter/pgfutter.go:67:17: too many errors
```
